### PR TITLE
Update to hyperkube 1.9.6 w/ cinder detach patch.

### PR DESCRIPTION
**Pull request by waynr**
This hyperkube is here:
https://quay.io/repository/rackspace/hyperkube?tab=tags

### CODE REVIEW

**Review by lblackstone — APPROVED** [review]
Do you have the image build process documented anywhere? I'm curious how the image compares to the coreos images, and if they made any tweaks that we need to incorporate.

+1 if CI passes

**Comment by waynr** [comment]
I haven't documented it anywhere yet, but i definitely should. I also need to create or push to an `rcbops` fork of kubernetes if it doesn't exist already. What do you think of updating this file with build instructions: https://github.com/rcbops/kubernetes-installer/blob/master/docs/dev-internal/custom-hyperkube.md

**Comment by lblackstone** [comment]
@waynr Sounds good. Looks like you may have already found https://github.com/rcbops/kubernetes

**Comment by lblackstone** [comment]
Ha, also realized that there's no CI on this repo... LGTM if you've tested the change

**Comment by waynr** [comment]
Gonna way to merge this PR until https://github.com/rcbops/kubernetes/pull/1 is merged and I have a chance to tag that repo according to the documentation here: https://github.com/waynr/kubernetes-installer/blob/d40e8654375fb6902414dc2bfe4f14711f873d0b/docs/dev-internal/custom-hyperkube.md

**Comment by waynr** [comment]
Okay I've finally verified this works after monkeying around with git tags for a while and going through the motions of rebuilding the hyperkube image. Gonna merge now.

**Pull request merged**
